# Generated by Django 2.1.4 on 2018-12-13 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicDomain',
            fields=[
                ('academic_domain_id', models.AutoField(primary_key=True, serialize=False)),
                ('cipcode', models.IntegerField()),
                ('ciptitle', models.CharField(db_column='CipTitle', max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'IPEDS Academic Program Domain',
                'verbose_name_plural': 'IPEDS Academic Program Domains',
                'db_table': 'academic_domain',
                'ordering': ['cipcode'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AcademicProgram',
            fields=[
                ('academic_program_id', models.AutoField(primary_key=True, serialize=False)),
                ('number_of_program_offered', models.IntegerField()),
            ],
            options={
                'verbose_name': 'IPEDS Academic Program Offered by Domains',
                'verbose_name_plural': 'IPEDS Academic Programs Offered by Domains',
                'db_table': 'academic_program',
                'ordering': ['institution_id', 'academic_domain_id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'city name',
                'verbose_name_plural': 'city names',
                'db_table': 'city',
                'ordering': ['city_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GraduationByRace',
            fields=[
                ('graduation_by_race_id', models.AutoField(primary_key=True, serialize=False)),
                ('number_of_graduation', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'IPEDS Institution Graduation by Race',
                'verbose_name_plural': 'IPEDS Institution Graduations by Race',
                'db_table': 'graduation_by_race',
                'ordering': ['institution_id', 'race_category_id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GraduationRaceType',
            fields=[
                ('graduation_race_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('race_category_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': ['IPEDS Institution Graduation Race Type'],
                'verbose_name_plural': ['IPEDS Institution Graduation Race Types'],
                'db_table': 'graduation_race_type',
                'ordering': ['race_category_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('institution_id', models.AutoField(primary_key=True, serialize=False)),
                ('unitid', models.IntegerField(blank=True, null=True, unique=True)),
                ('institution_name', models.CharField(max_length=255)),
                ('survey_year', models.CharField(max_length=4)),
                ('zip_code', models.CharField(blank=True, max_length=255, null=True)),
                ('student_faculty_ratio', models.DecimalField(decimal_places=0, max_digits=10)),
                ('percent_admitted', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'IPEDS Institution',
                'verbose_name_plural': 'IPEDS Institutions',
                'db_table': 'institution',
                'ordering': ['institution_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LibraryCollectionCategory',
            fields=[
                ('collection_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('collection_category_name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'IPEDS Institution Library Collection Category',
                'verbose_name_plural': 'IPEDS Institution Library Collection Categories',
                'db_table': 'library_collection_category',
                'ordering': ['collection_category_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LibraryCollectionHolding',
            fields=[
                ('library_collection_holding_id', models.AutoField(primary_key=True, serialize=False)),
                ('number_of_total_collection', models.IntegerField()),
            ],
            options={
                'verbose_name': 'IPEDS Institution Library Collection Holding',
                'verbose_name_plural': 'IPEDS Institution Library Collection Holdings',
                'db_table': 'library_collection_holding',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PeerComparison',
            fields=[
                ('peer_comparison_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'IPEDS Institution Peer Comparison',
                'verbose_name_plural': 'IPEDS Institution Peer Comparisons',
                'db_table': 'peer_comparison',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'state name',
                'verbose_name_plural': 'state names',
                'db_table': 'state',
                'ordering': ['state_name'],
                'managed': False,
            },
        ),
    ]
